// Copyright 2026 TidyVNC contributors. Licensed under GPL-2.0-or-later.
using System.Globalization;
using Microsoft.UI.Xaml.Markup;
using Microsoft.Windows.ApplicationModel.Resources;
using TidyVNC.Native;

namespace TidyVNC;

/// <summary>
/// The Windows string catalog (DECISIONS.md D20): Strings/en-US/Resources.resw,
/// generated by apps/windows/strings.py from the macOS catalog. Keys are the
/// macOS keys; the resource name replaces dots with underscores.
/// </summary>
internal static class Strings
{
    // Unpackaged builds name the PRI after the project; the default loader looks for resources.pri.
    private static readonly ResourceLoader Loader = File.Exists(Path.Combine(AppContext.BaseDirectory, "TidyVNC.pri"))
        ? new ResourceLoader(Path.Combine(AppContext.BaseDirectory, "TidyVNC.pri"), "Resources")
        : new ResourceLoader();

    public static string Get(string key)
    {
        var value = Loader.GetString(key.Replace('.', '_'));
        if (!string.IsNullOrEmpty(value)) return value;
        // The audit (strings.py) fails the build for unknown literal keys; this
        // guards computed ones without showing a blank label.
        System.Diagnostics.Debug.Fail($"Missing string {key}");
        return key;
    }

    public static string Format(string key, params object[] arguments) =>
        string.Format(CultureInfo.CurrentCulture, Get(key), arguments.Select(Argument).ToArray());

    public static string Resolve(NativeText text) =>
        text.Arguments.Count == 0 ? Get(text.Key) : Format(text.Key, [.. text.Arguments]);

    private static object Argument(object value) => value switch
    {
        NativeText text => Resolve(text),
        double number => number.ToString("0.##", CultureInfo.CurrentCulture),
        IFormattable number => number.ToString("N0", CultureInfo.CurrentCulture),
        _ => value,
    };
}

/// <summary>XAML access to the catalog: <c>{local:Str Key=history.recent.connections.title}</c>.</summary>
[MarkupExtensionReturnType(ReturnType = typeof(string))]
public sealed partial class Str : MarkupExtension
{
    public string Key { get; set; } = "";
    protected override object ProvideValue() => Strings.Get(Key);
}
