#!/usr/bin/env python3
"""Generate the C# interop layer for viewer/bridge/tidyvnc.h.

plans/native-ui-winui PLAN.md section 5: one [LibraryImport] per export and
blittable structs that mirror tidyvnc.h exactly. The generator keeps the two
in step; a layout probe (C, generated here too) prints every struct's size
and field offsets as the C compiler sees them, and the interop tests compare
them with the C# layout. Run after changing tidyvnc.h:

  python platform/windows/TidyVNC.Native/Bridge/generate-interop.py

Outputs (checked in):
  Bridge/Interop.g.cs      constants, structs and function declarations
  Bridge/abi-layout.g.c    sizeof/offsetof probe, built by tests/viewer
"""
from pathlib import Path
import re
import sys

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
HEADER = ROOT / "viewer/bridge/tidyvnc.h"

PRIMITIVES = {
    "uint8_t": "byte", "uint32_t": "uint", "int32_t": "int", "uint64_t": "ulong",
    "double": "double", "char": "byte", "tidyvnc_handle": "ulong", "tidyvnc_status": "uint",
    "void": "void",
}


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def cs_type(ctype, pointer):
    ctype = ctype.replace("const ", "").strip()
    base = PRIMITIVES.get(ctype, ctype)
    return base + "*" * pointer


def parse_constants(text):
    constants = []
    for name, value in re.findall(r"#define\s+(TIDYVNC_\w+)\s+(\d+)u?(?:ULL|u)?\b", text):
        kind = "ulong" if name.startswith("TIDYVNC_FEATURE_") else "uint"
        constants.append((name, kind, value))
    for body in re.findall(r"enum\s*\{(.*?)\}\s*;", text, flags=re.S):
        for entry in body.split(","):
            entry = entry.strip()
            if not entry:
                continue
            name, value = [part.strip() for part in entry.split("=")]
            kind = "ulong" if name.startswith("TIDYVNC_FEATURE_") else "uint"
            constants.append((name, kind, value))
    return constants


def parse_structs(text):
    structs = []
    for body, name in re.findall(r"typedef struct\s*\{(.*?)\}\s*(\w+)\s*;", text, flags=re.S):
        fields = []
        for declaration in [d.strip() for d in body.split(";") if d.strip()]:
            function = re.match(r"(\w+)\s*\(\s*\*\s*(\w+)\s*\)\s*\((.*)\)", declaration, flags=re.S)
            if function:
                result, field, parameters = function.groups()
                types = []
                for parameter in [p.strip() for p in parameters.split(",") if p.strip()]:
                    match = re.match(r"(const\s+)?(\w+)\s*(\**)", parameter)
                    types.append(cs_type(match.group(2), len(match.group(3))))
                types.append(PRIMITIVES.get(result, result))
                fields.append({"name": field, "cs": f"delegate* unmanaged[Cdecl]<{', '.join(types)}>", "count": None,
                               "kind": "function"})
                continue
            match = re.match(r"((?:const\s+)?\w+)\s*(.*)", declaration, flags=re.S)
            ctype, declarators = match.groups()
            for declarator in [d.strip() for d in declarators.split(",")]:
                m = re.match(r"(\**)\s*(\w+)\s*(?:\[(\d+)\])?$", declarator)
                pointer, field, count = len(m.group(1)), m.group(2), m.group(3)
                fields.append({"name": field, "cs": cs_type(ctype, pointer), "count": int(count) if count else None,
                               "ctype": ctype.replace("const ", "").strip(), "pointer": pointer})
        structs.append((name, fields))
    return structs


def parse_functions(text):
    functions = []
    for result, name, parameters in re.findall(r"TIDYVNC_API\s+(\w+)\s+(tidyvnc_\w+)\s*\((.*?)\)\s*;", text, flags=re.S):
        converted = []
        for index, parameter in enumerate([p.strip() for p in parameters.split(",") if p.strip() and p.strip() != "void"]):
            match = re.match(r"(const\s+)?(\w+)\s*(\**)\s*(\w+)?$", " ".join(parameter.split()))
            if not match:
                raise SystemExit(f"Unparsed parameter '{parameter}' in {name}")
            _, ctype, pointer, pname = match.groups()
            pname = pname or f"p{index}"
            if pname in ("out", "in", "ref", "object", "string", "base", "event", "operator", "params", "checked", "fixed"):
                pname = "@" + pname
            converted.append((cs_type(ctype, len(pointer)), pname))
        functions.append((PRIMITIVES.get(result, result), name, converted))
    return functions


PRIMITIVE_FIXED = {"byte", "uint", "int", "ulong", "double"}


def generate_cs(constants, structs, functions):
    lines = ["// <auto-generated>",
             "// Generated by Bridge/generate-interop.py from viewer/bridge/tidyvnc.h. Do not edit.",
             "// </auto-generated>",
             "#pragma warning disable CS0649, IDE1006, CA1707, CA1711, CA1716, CS8981",
             "using System.Runtime.CompilerServices;",
             "using System.Runtime.InteropServices;",
             "",
             "namespace TidyVNC.Native.Interop;",
             "",
             "/// <summary>Constants from tidyvnc.h, with their C names.</summary>",
             "public static class Tidyvnc",
             "{"]
    for name, kind, value in constants:
        suffix = "UL" if kind == "ulong" else "U"
        lines.append(f"    public const {kind} {name} = {value}{suffix};")
    lines += ["}", ""]
    inline_arrays = {}
    for name, fields in structs:
        lines.append(f"[StructLayout(LayoutKind.Sequential)]")
        lines.append(f"public unsafe partial struct {name}")
        lines.append("{")
        for field in fields:
            if field.get("kind") == "function":
                lines.append(f"    public {field['cs']} {field['name']};")
            elif field["count"] is not None and field["cs"] in PRIMITIVE_FIXED:
                lines.append(f"    public fixed {field['cs']} {field['name']}[{field['count']}];")
            elif field["count"] is not None:
                array = f"{field['cs']}_Array{field['count']}"
                inline_arrays[array] = (field["cs"], field["count"])
                lines.append(f"    public {array} {field['name']};")
            else:
                lines.append(f"    public {field['cs']} {field['name']};")
        lines += ["}", ""]
    for array, (element, count) in sorted(inline_arrays.items()):
        lines += [f"[InlineArray({count})]", f"public struct {array}", "{", f"    private {element} _element0;", "}", ""]
    lines += ["/// <summary>Every tidyvnc_viewer.dll export, in header order.</summary>",
              "public static unsafe partial class NativeMethods",
              "{",
              "    public const string Library = \"tidyvnc_viewer\";"]
    for result, name, parameters in functions:
        signature = ", ".join(f"{t} {n}" for t, n in parameters)
        lines += ["", f"    [LibraryImport(Library)]",
                  "    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]",
                  f"    public static partial {result} {name}({signature});"]
    lines += ["}", ""]
    return "\n".join(lines)


def generate_probe(structs):
    lines = ["/* Generated by Bridge/generate-interop.py from viewer/bridge/tidyvnc.h. Do not edit. */",
             "/* Prints the C layout of every tidyvnc.h struct for the C# interop tests. */",
             "#include <stddef.h>", "#include <stdio.h>", "#define TIDYVNC_STATIC", "#include <tidyvnc.h>",
             "int main(void)", "{", '  printf("{\\n");']
    for index, (name, fields) in enumerate(structs):
        lines.append(f'  printf("  \\"{name}\\": {{\\"size\\": %zu, \\"fields\\": {{", sizeof({name}));')
        for findex, field in enumerate(fields):
            comma = "," if findex + 1 < len(fields) else ""
            lines.append(f'  printf("\\"{field["name"]}\\": %zu{comma}", offsetof({name}, {field["name"]}));')
        tail = "," if index + 1 < len(structs) else ""
        lines.append(f'  printf("}}}}{tail}\\n");')
    lines += ['  printf("}\\n");', "  return 0;", "}", ""]
    return "\n".join(lines)


def main():
    text = strip_comments(HEADER.read_text(encoding="utf-8"))
    constants = parse_constants(text)
    structs = parse_structs(text)
    functions = parse_functions(text)
    declared = len(re.findall(r"^TIDYVNC_API ", HEADER.read_text(encoding="utf-8"), flags=re.M))
    if len(functions) != declared:
        raise SystemExit(f"Parsed {len(functions)} functions but the header declares {declared}")
    (HERE / "Interop.g.cs").write_text(generate_cs(constants, structs, functions), encoding="utf-8", newline="\n")
    (HERE / "abi-layout.g.c").write_text(generate_probe(structs), encoding="utf-8", newline="\n")
    print(f"{len(constants)} constants, {len(structs)} structs, {len(functions)} functions")


if __name__ == "__main__":
    sys.exit(main())
