// <auto-generated>
// Generated by Bridge/generate-interop.py from viewer/bridge/tidyvnc.h. Do not edit.
// </auto-generated>
#pragma warning disable CS0649, IDE1006, CA1707, CA1711, CA1716, CS8981
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace TidyVNC.Native.Interop;

/// <summary>Constants from tidyvnc.h, with their C names.</summary>
public static class Tidyvnc
{
    public const uint TIDYVNC_ABI_VERSION = 1U;
    public const ulong TIDYVNC_FEATURE_CANVAS_GEOMETRY = 2147483648UL;
    public const ulong TIDYVNC_FEATURE_CONNECTION_DOCUMENT = 4294967296UL;
    public const ulong TIDYVNC_FEATURE_DOCUMENT_OPTIONS = 8589934592UL;
    public const ulong TIDYVNC_FEATURE_INVOCATION_SYNTAX = 17179869184UL;
    public const ulong TIDYVNC_FEATURE_INVOCATION_VALUES = 34359738368UL;
    public const ulong TIDYVNC_FEATURE_INPUT_TIMING = 68719476736UL;
    public const ulong TIDYVNC_FEATURE_MESSAGE_LIMITS = 137438953472UL;
    public const ulong TIDYVNC_FEATURE_WINDOW_GEOMETRY = 274877906944UL;
    public const ulong TIDYVNC_FEATURE_PROCESS_LOGGING = 549755813888UL;
    public const ulong TIDYVNC_FEATURE_FILE_LOGGING = 1099511627776UL;
    public const ulong TIDYVNC_FEATURE_PASSWORD_FILE_REPLY = 2199023255552UL;
    public const ulong TIDYVNC_FEATURE_CREDENTIAL_BYTES = 4398046511104UL;
    public const ulong TIDYVNC_FEATURE_LISTENER = 8796093022208UL;
    public const ulong TIDYVNC_FEATURE_ROUTED_CONNECT = 17592186044416UL;
    public const ulong TIDYVNC_FEATURE_VIEWPORT_DIAGNOSTICS = 35184372088832UL;
    public const ulong TIDYVNC_FEATURE_PARAMETER_GRAMMARS = 70368744177664UL;
    public const ulong TIDYVNC_FEATURE_NATIVE_ERROR_CATEGORY = 140737488355328UL;
    public const ulong TIDYVNC_FEATURE_IDENTITY_DIGEST = 281474976710656UL;
    public const uint TIDYVNC_OK = 0U;
    public const uint TIDYVNC_NO_CHANGE = 1U;
    public const uint TIDYVNC_PENDING = 2U;
    public const uint TIDYVNC_INVALID_ARGUMENT = 10U;
    public const uint TIDYVNC_ABI_MISMATCH = 11U;
    public const uint TIDYVNC_UNSUPPORTED = 12U;
    public const uint TIDYVNC_INVALID_HANDLE = 13U;
    public const uint TIDYVNC_WRONG_HANDLE_TYPE = 14U;
    public const uint TIDYVNC_RESOURCE_LIMIT = 15U;
    public const uint TIDYVNC_OUT_OF_MEMORY = 16U;
    public const uint TIDYVNC_STALE = 17U;
    public const uint TIDYVNC_NOT_CONNECTED = 18U;
    public const uint TIDYVNC_CLOSING = 19U;
    public const uint TIDYVNC_BUSY = 20U;
    public const uint TIDYVNC_QUEUE_FULL = 21U;
    public const uint TIDYVNC_CANCELLED = 22U;
    public const uint TIDYVNC_NOT_PENDING = 23U;
    public const uint TIDYVNC_FAILED = 24U;
    public const uint TIDYVNC_INTERNAL = 25U;
    public const uint TIDYVNC_VIEW_ONLY = 26U;
    public const uint TIDYVNC_UNFOCUSED = 27U;
    public const uint TIDYVNC_DISABLED = 28U;
    public const uint TIDYVNC_ECHO = 29U;
    public const uint TIDYVNC_DOMAIN_BRIDGE = 1U;
    public const uint TIDYVNC_DOMAIN_ENDPOINT = 2U;
    public const uint TIDYVNC_DOMAIN_OPERATION = 3U;
    public const uint TIDYVNC_DOMAIN_INPUT = 4U;
    public const uint TIDYVNC_DOMAIN_AUTHENTICATION = 5U;
    public const uint TIDYVNC_DOMAIN_ENCODING = 6U;
    public const uint TIDYVNC_DOMAIN_SECURITY = 7U;
    public const uint TIDYVNC_DOMAIN_DOCUMENT = 8U;
    public const uint TIDYVNC_DOMAIN_INVOCATION = 9U;
    public const uint TIDYVNC_DOMAIN_LOGGING = 10U;
    public const uint TIDYVNC_DOMAIN_IDENTITY = 11U;
    public const uint TIDYVNC_ENDPOINT_TOO_LONG = 1U;
    public const uint TIDYVNC_ENDPOINT_INVALID_HOST = 2U;
    public const uint TIDYVNC_ENDPOINT_UNMATCHED_BRACKET = 3U;
    public const uint TIDYVNC_ENDPOINT_INVALID_PORT = 4U;
    public const uint TIDYVNC_ENDPOINT_INVALID_PATH = 5U;
    public const uint TIDYVNC_ENDPOINT_INVALID_ROUTE = 6U;
    public const uint TIDYVNC_ENDPOINT_UNSUPPORTED_TRANSPORT = 7U;
    public const ulong TIDYVNC_FEATURE_RUNTIME = 1UL;
    public const ulong TIDYVNC_FEATURE_TCP_UNIX_CONNECT = 2UL;
    public const ulong TIDYVNC_FEATURE_EVENT_POLL = 4UL;
    public const ulong TIDYVNC_FEATURE_IMAGES = 8UL;
    public const ulong TIDYVNC_FEATURE_INPUT = 16UL;
    public const ulong TIDYVNC_FEATURE_PROMPTS = 32UL;
    public const ulong TIDYVNC_FEATURE_CALLBACKS = 64UL;
    public const ulong TIDYVNC_FEATURE_GEOMETRY = 128UL;
    public const ulong TIDYVNC_FEATURE_CLIPBOARD = 256UL;
    public const ulong TIDYVNC_FEATURE_ENCODING = 512UL;
    public const ulong TIDYVNC_FEATURE_ENDPOINT_VALIDATION = 1024UL;
    public const ulong TIDYVNC_FEATURE_SCALING = 2048UL;
    public const ulong TIDYVNC_FEATURE_TILE_RENDERER = 4096UL;
    public const ulong TIDYVNC_FEATURE_DAMAGE_GEOMETRY = 8192UL;
    public const ulong TIDYVNC_FEATURE_CURSOR_RENDERER = 16384UL;
    public const ulong TIDYVNC_FEATURE_INPUT_POLICY = 32768UL;
    public const ulong TIDYVNC_FEATURE_SHORTCUTS = 65536UL;
    public const ulong TIDYVNC_FEATURE_INPUT_RELEASE = 131072UL;
    public const ulong TIDYVNC_FEATURE_CONNECTION_INFO = 262144UL;
    public const ulong TIDYVNC_FEATURE_ENDPOINT_IDENTITY = 524288UL;
    public const ulong TIDYVNC_FEATURE_PROMPT_SECURITY = 1048576UL;
    public const ulong TIDYVNC_FEATURE_CERTIFICATE_POLICY = 2097152UL;
    public const ulong TIDYVNC_FEATURE_CERTIFICATE_KEY = 4194304UL;
    public const ulong TIDYVNC_FEATURE_HOST_KEY_ENCODING = 8388608UL;
    public const ulong TIDYVNC_FEATURE_REQUIRED_TLS_FILES = 16777216UL;
    public const ulong TIDYVNC_FEATURE_SECURITY_SELECTION = 33554432UL;
    public const ulong TIDYVNC_FEATURE_TLS_PRIORITY_VALIDATION = 67108864UL;
    public const ulong TIDYVNC_FEATURE_SECURITY_RECONFIGURATION = 134217728UL;
    public const ulong TIDYVNC_FEATURE_SHARED_SESSION = 268435456UL;
    public const ulong TIDYVNC_FEATURE_DESKTOP_LAYOUT = 536870912UL;
    public const ulong TIDYVNC_FEATURE_DISPLAY_LAYOUT = 1073741824UL;
    public const uint TIDYVNC_LOGGING_TOO_LARGE = 1U;
    public const uint TIDYVNC_LOGGING_NULL_BYTE = 2U;
    public const uint TIDYVNC_LOGGING_INVALID_RULE = 3U;
    public const uint TIDYVNC_LOGGING_LEVEL_OVERFLOW = 4U;
    public const uint TIDYVNC_LOGGING_UNKNOWN_WRITER = 5U;
    public const uint TIDYVNC_LOGGING_UNKNOWN_TARGET = 6U;
    public const uint TIDYVNC_LOGGING_INVALID_CATALOG = 7U;
    public const uint TIDYVNC_LOGGING_FROZEN = 8U;
    public const uint TIDYVNC_LOGGING_INVALID_FILE_PATH = 9U;
    public const uint TIDYVNC_INVOCATION_LAUNCH = 0U;
    public const uint TIDYVNC_INVOCATION_HELP = 1U;
    public const uint TIDYVNC_INVOCATION_VERSION = 2U;
    public const uint TIDYVNC_INVOCATION_TOO_MANY_ARGUMENTS = 1U;
    public const uint TIDYVNC_INVOCATION_TOO_LARGE = 2U;
    public const uint TIDYVNC_INVOCATION_NULL_BYTE = 3U;
    public const uint TIDYVNC_INVOCATION_UNKNOWN_OPTION = 4U;
    public const uint TIDYVNC_INVOCATION_MISSING_VALUE = 5U;
    public const uint TIDYVNC_INVOCATION_UNAVAILABLE = 6U;
    public const uint TIDYVNC_INVOCATION_EXTRA_OPERAND = 7U;
    public const uint TIDYVNC_INVOCATION_INVALID_VALUE = 9U;
    public const uint TIDYVNC_INVOCATION_CONNECTION = 0U;
    public const uint TIDYVNC_INVOCATION_ENCODING = 1U;
    public const uint TIDYVNC_INVOCATION_INPUT = 2U;
    public const uint TIDYVNC_INVOCATION_DISPLAY = 3U;
    public const uint TIDYVNC_INVOCATION_SECURITY = 4U;
    public const uint TIDYVNC_INVOCATION_CREDENTIAL_FILE = 5U;
    public const uint TIDYVNC_INVOCATION_LOGGING = 6U;
    public const uint TIDYVNC_INVOCATION_NETWORK = 7U;
    public const uint TIDYVNC_INVOCATION_LISTEN = 8U;
    public const uint TIDYVNC_INVOCATION_TUNNEL = 9U;
    public const uint TIDYVNC_INVOCATION_PLATFORM = 10U;
    public const uint TIDYVNC_DOCUMENT_EMPTY = 1U;
    public const uint TIDYVNC_DOCUMENT_INVALID_HEADER = 2U;
    public const uint TIDYVNC_DOCUMENT_NULL_BYTE = 3U;
    public const uint TIDYVNC_DOCUMENT_LINE_TOO_LONG = 4U;
    public const uint TIDYVNC_DOCUMENT_INVALID_ASSIGNMENT = 5U;
    public const uint TIDYVNC_DOCUMENT_INVALID_ESCAPE = 6U;
    public const uint TIDYVNC_DOCUMENT_TOO_LARGE = 7U;
    public const uint TIDYVNC_DOCUMENT_TOO_MANY_ENTRIES = 8U;
    public const uint TIDYVNC_DOCUMENT_INVALID_EXPORT_NAME = 9U;
    public const uint TIDYVNC_DOCUMENT_INVALID_VALUE = 12U;
    public const uint TIDYVNC_DOCUMENT_UNAVAILABLE = 13U;
    public const uint TIDYVNC_ENDPOINT_TCP = 1U;
    public const uint TIDYVNC_ENDPOINT_UNIX = 2U;
    public const uint TIDYVNC_SECURITY_UNKNOWN_TYPE = 1U;
    public const uint TIDYVNC_SECURITY_UNAVAILABLE = 2U;
    public const uint TIDYVNC_SECURITY_TOO_LONG = 3U;
    public const uint TIDYVNC_SECURITY_INVALID_SYNTAX = 4U;
    public const uint TIDYVNC_SECURITY_INVALID_TLS_PRIORITY = 5U;
    public const uint TIDYVNC_SECURITY_UNENCRYPTED = 0U;
    public const uint TIDYVNC_SECURITY_ANONYMOUS_TLS = 1U;
    public const uint TIDYVNC_SECURITY_X509_TLS = 2U;
    public const uint TIDYVNC_SECURITY_RSA_AES = 3U;
    public const uint TIDYVNC_SECURITY_RSA_AUTHENTICATION = 4U;
    public const uint TIDYVNC_SECURITY_LEGACY_AUTHENTICATION = 5U;
    public const uint TIDYVNC_SECURITY_NO_CREDENTIALS = 0U;
    public const uint TIDYVNC_SECURITY_PASSWORD = 1U;
    public const uint TIDYVNC_SECURITY_USERNAME_PASSWORD = 2U;
    public const uint TIDYVNC_SECURITY_SERVER_SELECTED = 3U;
    public const uint TIDYVNC_ENCODING_AUTO_SELECT = 0U;
    public const uint TIDYVNC_ENCODING_FULL_COLOR = 1U;
    public const uint TIDYVNC_ENCODING_LOW_COLOR_LEVEL = 2U;
    public const uint TIDYVNC_ENCODING_PREFERRED = 3U;
    public const uint TIDYVNC_ENCODING_CUSTOM_COMPRESSION = 4U;
    public const uint TIDYVNC_ENCODING_COMPRESSION = 5U;
    public const uint TIDYVNC_ENCODING_NO_JPEG = 6U;
    public const uint TIDYVNC_ENCODING_QUALITY = 7U;
    public const uint TIDYVNC_OPTION_BOOLEAN = 0U;
    public const uint TIDYVNC_OPTION_INTEGER = 1U;
    public const uint TIDYVNC_OPTION_ENUMERATION = 2U;
    public const uint TIDYVNC_SOURCE_COMPILED = 0U;
    public const uint TIDYVNC_SOURCE_APP_DEFAULTS = 1U;
    public const uint TIDYVNC_SOURCE_PROFILE = 2U;
    public const uint TIDYVNC_SOURCE_SESSION = 3U;
    public const uint TIDYVNC_SOURCE_COMMAND_LINE = 4U;
    public const uint TIDYVNC_SOURCE_DOCUMENT = 5U;
    public const uint TIDYVNC_ENCODING_UNKNOWN_OPTION = 1U;
    public const uint TIDYVNC_ENCODING_INVALID_VALUE = 2U;
    public const uint TIDYVNC_ENCODING_UNAVAILABLE = 3U;
    public const uint TIDYVNC_ENCODING_TOO_LONG = 4U;
    public const uint TIDYVNC_LISTENER_STARTING = 0U;
    public const uint TIDYVNC_LISTENER_LISTENING = 1U;
    public const uint TIDYVNC_LISTENER_STOPPING = 2U;
    public const uint TIDYVNC_LISTENER_CLOSED = 3U;
    public const uint TIDYVNC_LISTENER_FAILED = 4U;
    public const uint TIDYVNC_LISTENER_STATE = 0U;
    public const uint TIDYVNC_LISTENER_INCOMING = 1U;
    public const uint TIDYVNC_LISTENER_ACCEPTED = 2U;
    public const uint TIDYVNC_LISTENER_REJECTED = 3U;
    public const uint TIDYVNC_LISTENER_EXPIRED = 4U;
    public const uint TIDYVNC_LISTENER_ERROR_NONE = 0U;
    public const uint TIDYVNC_LISTENER_ERROR_CANCELLED = 1U;
    public const uint TIDYVNC_LISTENER_ERROR_BIND = 2U;
    public const uint TIDYVNC_LISTENER_ERROR_ACCEPT = 3U;
    public const uint TIDYVNC_LISTENER_ERROR_INVALID_ADDRESS = 4U;
    public const uint TIDYVNC_LISTENER_ERROR_UNSUPPORTED = 5U;
    public const uint TIDYVNC_LISTENER_ERROR_EVENT_OVERFLOW = 6U;
    public const uint TIDYVNC_LISTENER_ERROR_INTERNAL = 7U;
    public const uint TIDYVNC_WINDOW_GEOMETRY_SIZE = 1U;
    public const uint TIDYVNC_WINDOW_GEOMETRY_POSITION = 2U;
    public const uint TIDYVNC_STATE_IDLE = 0U;
    public const uint TIDYVNC_STATE_RESOLVING = 1U;
    public const uint TIDYVNC_STATE_CONNECTING = 2U;
    public const uint TIDYVNC_STATE_NEGOTIATING = 3U;
    public const uint TIDYVNC_STATE_AUTHENTICATING = 4U;
    public const uint TIDYVNC_STATE_CONNECTED = 5U;
    public const uint TIDYVNC_STATE_DISCONNECTING = 6U;
    public const uint TIDYVNC_STATE_CLOSED = 7U;
    public const uint TIDYVNC_STATE_FAILED = 8U;
    public const uint TIDYVNC_END_NONE = 0U;
    public const uint TIDYVNC_END_CANCELLED = 1U;
    public const uint TIDYVNC_END_PEER_CLOSED = 2U;
    public const uint TIDYVNC_END_PROMPT_TIMEOUT = 3U;
    public const uint TIDYVNC_END_AUTH_REJECTED = 4U;
    public const uint TIDYVNC_END_TRANSPORT = 5U;
    public const uint TIDYVNC_END_PROTOCOL = 6U;
    public const uint TIDYVNC_END_RESOURCE = 7U;
    public const uint TIDYVNC_END_INTERNAL = 8U;
    public const uint TIDYVNC_END_EVENT_OVERFLOW = 9U;
    public const uint TIDYVNC_END_RESOLUTION = 10U;
    public const uint TIDYVNC_END_CONNECTION = 11U;
    public const uint TIDYVNC_END_RESOLUTION_TIMEOUT = 12U;
    public const uint TIDYVNC_END_CONNECTION_TIMEOUT = 13U;
    public const uint TIDYVNC_END_UNSUPPORTED_ENDPOINT = 14U;
    public const uint TIDYVNC_END_INVALID_ENDPOINT = 15U;
    public const uint TIDYVNC_EVENT_SNAPSHOT = 0U;
    public const uint TIDYVNC_EVENT_STATE = 1U;
    public const uint TIDYVNC_EVENT_DESKTOP = 2U;
    public const uint TIDYVNC_EVENT_BELL = 3U;
    public const uint TIDYVNC_EVENT_STATISTICS = 4U;
    public const uint TIDYVNC_EVENT_COMPLETION = 5U;
    public const uint TIDYVNC_EVENT_OVERFLOW = 6U;
    public const uint TIDYVNC_OPERATION_SUCCEEDED = 0U;
    public const uint TIDYVNC_OPERATION_CANCELLED = 1U;
    public const uint TIDYVNC_OPERATION_FAILED = 2U;
    public const uint TIDYVNC_OPERATION_FAILURE_NONE = 0U;
    public const uint TIDYVNC_OPERATION_TIMED_OUT = 1U;
    public const uint TIDYVNC_OPERATION_SERVER_REJECTED = 2U;
    public const uint TIDYVNC_PIXEL_BGRA8 = 1U;
    public const uint TIDYVNC_PIXEL_RGBA8 = 2U;
    public const uint TIDYVNC_ALPHA_OPAQUE = 1U;
    public const uint TIDYVNC_ALPHA_STRAIGHT = 2U;
    public const uint TIDYVNC_ALPHA_PREMULTIPLIED = 3U;
    public const uint TIDYVNC_ORIGIN_TOP_LEFT = 1U;
    public const uint TIDYVNC_PROMPT_CREDENTIALS = 1U;
    public const uint TIDYVNC_PROMPT_CERTIFICATE = 2U;
    public const uint TIDYVNC_PROMPT_HOST_KEY = 3U;
    public const uint TIDYVNC_CERT_INVALID = 1U;
    public const uint TIDYVNC_CERT_REVOKED = 2U;
    public const uint TIDYVNC_CERT_UNKNOWN_ISSUER = 4U;
    public const uint TIDYVNC_CERT_SIGNER_NOT_CA = 8U;
    public const uint TIDYVNC_CERT_WEAK_ALGORITHM = 16U;
    public const uint TIDYVNC_CERT_NOT_YET_VALID = 32U;
    public const uint TIDYVNC_CERT_EXPIRED = 64U;
    public const uint TIDYVNC_CERT_BAD_SIGNATURE = 128U;
    public const uint TIDYVNC_CERT_OLD_REVOCATION_DATA = 256U;
    public const uint TIDYVNC_CERT_WRONG_OWNER = 512U;
    public const uint TIDYVNC_CERT_FUTURE_REVOCATION_DATA = 1024U;
    public const uint TIDYVNC_CERT_SIGNER_CONSTRAINTS = 2048U;
    public const uint TIDYVNC_CERT_MISMATCH = 4096U;
    public const uint TIDYVNC_CERT_WRONG_PURPOSE = 8192U;
    public const uint TIDYVNC_CERT_MISSING_OCSP = 16384U;
    public const uint TIDYVNC_CERT_INVALID_OCSP = 32768U;
    public const uint TIDYVNC_CERT_CRITICAL_EXTENSION = 65536U;
    public const uint TIDYVNC_CERT_UNKNOWN_PROBLEM = 131072U;
    public const uint TIDYVNC_CERT_MISSING_PROBLEM = 262144U;
    public const uint TIDYVNC_SCALING_UNSCALED = 0U;
    public const uint TIDYVNC_SCALING_AUTO = 1U;
    public const uint TIDYVNC_SCALING_FIXED_RATIO = 2U;
    public const uint TIDYVNC_SCALING_FIT_WIDTH = 3U;
    public const uint TIDYVNC_SCALING_FIT_HEIGHT = 4U;
    public const uint TIDYVNC_SCALING_EXACT = 5U;
    public const uint TIDYVNC_SCALING_PERCENT = 6U;
    public const uint TIDYVNC_SCALING_INDEPENDENT = 7U;
    public const uint TIDYVNC_FILTER_NEAREST = 0U;
    public const uint TIDYVNC_FILTER_BILINEAR = 1U;
    public const uint TIDYVNC_FILTER_AREA = 2U;
    public const uint TIDYVNC_CLIPBOARD_OFFERED = 1U;
    public const uint TIDYVNC_CLIPBOARD_TEXT = 2U;
    public const uint TIDYVNC_CLIPBOARD_UNAVAILABLE = 3U;
    public const uint TIDYVNC_CLIPBOARD_INVALIDATED = 4U;
    public const uint TIDYVNC_CLIPBOARD_REJECTED = 5U;
    public const uint TIDYVNC_NATIVE_ERROR_OTHER = 0U;
    public const uint TIDYVNC_NATIVE_ERROR_NETWORK_POLICY = 1U;
    public const uint TIDYVNC_NATIVE_ERROR_REFUSED = 2U;
    public const uint TIDYVNC_NATIVE_ERROR_ROUTING = 3U;
    public const uint TIDYVNC_NATIVE_ERROR_TIMED_OUT = 4U;
    public const uint TIDYVNC_IDENTITY_CREDENTIAL = 1U;
    public const uint TIDYVNC_IDENTITY_TRUST_CERTIFICATE = 2U;
    public const uint TIDYVNC_IDENTITY_TRUST_HOST_KEY = 3U;
    public const uint TIDYVNC_IDENTITY_SSH_ROUTE = 4U;
    public const uint TIDYVNC_IDENTITY_SSH_INTENT = 5U;
    public const uint TIDYVNC_IDENTITY_SSH_RESOLVED = 6U;
    public const uint TIDYVNC_IDENTITY_PASSWORD_ONLY = 1U;
    public const uint TIDYVNC_IDENTITY_USERNAME_PASSWORD = 2U;
    public const uint TIDYVNC_IDENTITY_TOO_LONG = 1U;
    public const uint TIDYVNC_IDENTITY_INVALID_TEXT = 2U;
    public const uint TIDYVNC_IDENTITY_INVALID_ENDPOINT = 3U;
    public const uint TIDYVNC_IDENTITY_INVALID_AUTHENTICATION = 4U;
    public const uint TIDYVNC_IDENTITY_UNEXPECTED_USERNAME = 5U;
    public const uint TIDYVNC_IDENTITY_INVALID_GATEWAY = 6U;
    public const uint TIDYVNC_IDENTITY_INVALID_ALIAS = 7U;
    public const uint TIDYVNC_IDENTITY_INVALID_KIND = 8U;
    public const uint TIDYVNC_SSH_GATEWAY_USER = 1U;
    public const uint TIDYVNC_SSH_GATEWAY_EXPLICIT_PORT = 2U;
    public const uint TIDYVNC_DESKTOP_SIZE_LEGACY = 1U;
    public const uint TIDYVNC_DESKTOP_SIZE_STRICT = 2U;
    public const uint TIDYVNC_SHORTCUT_NORMAL = 0U;
    public const uint TIDYVNC_SHORTCUT_UNARM = 1U;
    public const uint TIDYVNC_SHORTCUT_ACTION = 2U;
    public const uint TIDYVNC_SHORTCUT_IGNORE = 3U;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_bytes
{
    public byte* data;
    public ulong length;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_invocation_info
{
    public uint size;
    public uint version;
    public uint action;
    public uint count;
    public uint operand_argument;
    public uint reserved;
    public tidyvnc_bytes operand;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_invocation_assignment
{
    public uint size;
    public uint version;
    public uint category;
    public uint argument;
    public uint value_argument;
    public uint reserved;
    public fixed byte name[64];
    public tidyvnc_bytes value;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_invocation_option
{
    public uint size;
    public uint version;
    public uint category;
    public uint boolean;
    public uint available;
    public uint reserved;
    public fixed byte name[64];
    public fixed byte alias[64];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_document_info
{
    public uint size;
    public uint version;
    public uint count;
    public uint legacy_header;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_document_entry
{
    public uint size;
    public uint version;
    public uint line;
    public uint reserved;
    public fixed byte name[255];
    public fixed byte value[256];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_document_assignment
{
    public tidyvnc_bytes name;
    public tidyvnc_bytes value;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_sharing
{
    public uint size;
    public uint version;
    public uint shared;
    public uint editable;
    public ulong revision;
    public ulong generation;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_security_configuration
{
    public uint size;
    public uint version;
    public uint editable;
    public uint reserved;
    public ulong revision;
    public ulong generation;
    public uint tls_priority_length;
    public uint ca_file_length;
    public uint crl_file_length;
    public uint reserved2;
    public fixed byte types[1025];
    public fixed byte tls_priority[4096];
    public fixed byte ca_file[4096];
    public fixed byte crl_file[4096];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_security_update
{
    public uint size;
    public uint version;
    public tidyvnc_bytes types;
    public tidyvnc_bytes tls_priority;
    public tidyvnc_bytes ca_file;
    public tidyvnc_bytes crl_file;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_mutable_bytes
{
    public byte* data;
    public ulong length;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_endpoint_info
{
    public uint size;
    public uint version;
    public uint transport;
    public uint port;
    public tidyvnc_bytes host;
    public tidyvnc_bytes scope;
    public tidyvnc_bytes path;
    public tidyvnc_bytes route;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_security_choice
{
    public uint size;
    public uint version;
    public uint type;
    public uint available;
    public uint protection;
    public uint credentials;
    public uint aes_bits;
    public uint reserved;
    public fixed byte name[32];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_security_selection
{
    public uint size;
    public uint version;
    public uint count;
    public uint reserved;
    public fixed uint types[32];
    public fixed byte canonical[1025];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_encoding_assignment
{
    public tidyvnc_bytes name;
    public tidyvnc_bytes value;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_encoding_schema
{
    public uint size;
    public uint version;
    public uint id;
    public uint type;
    public int minimum;
    public int maximum;
    public uint persistent;
    public uint live;
    public fixed byte name[32];
    public fixed byte alias[32];
    public fixed byte default_value[32];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_encoding_choice
{
    public uint size;
    public uint version;
    public uint available;
    public int wire_encoding;
    public fixed byte name[32];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_encoding_value
{
    public uint size;
    public uint version;
    public uint id;
    public uint source;
    public fixed byte value[32];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_error
{
    public uint size;
    public uint version;
    public uint code;
    public uint domain;
    public uint detail;
    public int native_error;
    public fixed byte message[160];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_abi_info
{
    public uint size;
    public uint version;
    public ulong features;
    public uint handle_capacity;
    public uint runtime_capacity;
    public uint security_count;
    public uint reserved;
    public fixed uint security_types[32];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_runtime_options
{
    public uint size;
    public uint version;
    public uint session_capacity;
    public uint reserved;
    public ulong required_features;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_listener_options
{
    public uint size;
    public uint version;
    public uint port;
    public uint ipv4;
    public uint ipv6;
    public uint backlog;
    public uint pending_capacity;
    public uint event_capacity;
    public uint pending_timeout_ms;
    public uint reserved;
    public tidyvnc_bytes address;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_listener_address
{
    public fixed byte host[64];
    public uint port;
    public uint reserved;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_listener_snapshot
{
    public uint size;
    public uint version;
    public uint state;
    public uint error;
    public int native_error;
    public uint pending;
    public uint address_count;
    public uint reserved;
    public tidyvnc_listener_address_Array2 addresses;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_listener_event
{
    public uint size;
    public uint version;
    public uint kind;
    public uint reserved;
    public ulong sequence;
    public ulong incoming_id;
    public tidyvnc_listener_address peer;
    public tidyvnc_listener_snapshot snapshot;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_session_options
{
    public uint size;
    public uint version;
    public uint security_count;
    public fixed uint security_types[32];
    public uint prompt_timeout_ms;
    public uint event_capacity;
    public uint command_capacity;
    public uint reserved;
    public ulong framebuffer_bytes;
    public ulong publication_bytes;
    public tidyvnc_bytes tls_priority;
    public tidyvnc_bytes ca_file;
    public tidyvnc_bytes crl_file;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_input_timing
{
    public uint size;
    public uint version;
    public uint pointer_interval_ms;
    public uint reserved;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_message_limits
{
    public uint size;
    public uint version;
    public uint max_cut_text;
    public uint reserved;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_window_geometry
{
    public uint size;
    public uint version;
    public uint flags;
    public uint reserved;
    public int width;
    public int height;
    public int x;
    public int y;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_connect_options
{
    public uint size;
    public uint version;
    public uint ipv4;
    public uint ipv6;
    public uint resolve_timeout_ms;
    public uint connect_timeout_ms;
    public uint address_timeout_ms;
    public uint reserved;
    public tidyvnc_bytes endpoint;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_operation
{
    public uint size;
    public uint version;
    public ulong operation;
    public ulong generation;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_snapshot
{
    public uint size;
    public uint version;
    public uint state;
    public uint end_reason;
    public int native_error;
    public uint width;
    public uint height;
    public uint supports_resize;
    public uint resize_pending;
    public uint reserved;
    public ulong generation;
    public ulong frames;
    public ulong bells;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_remote_screen
{
    public uint id;
    public uint x;
    public uint y;
    public uint width;
    public uint height;
    public uint flags;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_desktop_layout_request
{
    public uint size;
    public uint version;
    public uint width;
    public uint height;
    public uint screen_count;
    public uint reserved;
    public tidyvnc_remote_screen* screens;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_desktop_layout
{
    public uint size;
    public uint version;
    public uint screen_count;
    public uint reserved;
    public tidyvnc_snapshot snapshot;
    public tidyvnc_remote_screen_Array255 screens;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_display_monitor
{
    public uint id;
    public int x;
    public int y;
    public uint width;
    public uint height;
    public uint backing_width;
    public uint backing_height;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_display_layout_request
{
    public uint size;
    public uint version;
    public uint monitor_count;
    public uint device_pixels;
    public tidyvnc_display_monitor* monitors;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_display_layout
{
    public uint size;
    public uint version;
    public uint width;
    public uint height;
    public uint screen_count;
    public uint normalized;
    public tidyvnc_remote_screen_Array64 screens;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_connection_info
{
    public uint size;
    public uint version;
    public uint protocol_major;
    public uint protocol_minor;
    public uint security_type;
    public uint credentials_secure;
    public uint name_truncated;
    public uint reserved;
    public int requested_encoding;
    public int last_encoding;
    public ulong bits_per_second;
    public tidyvnc_snapshot snapshot;
    public fixed byte desktop_name[1025];
    public fixed byte pixel_format[128];
    public fixed byte security_name[64];
    public fixed byte requested_encoding_name[32];
    public fixed byte last_encoding_name[32];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_event
{
    public uint size;
    public uint version;
    public uint kind;
    public uint result;
    public uint failure;
    public uint native_result;
    public ulong sequence;
    public ulong operation;
    public ulong origin;
    public tidyvnc_snapshot snapshot;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_view_update
{
    public uint size;
    public uint version;
    public uint frame_changed;
    public uint cursor_changed;
    public ulong generation;
    public ulong frame;
    public ulong cursor;
    public uint damage_x;
    public uint damage_y;
    public uint damage_width;
    public uint damage_height;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_image_info
{
    public uint size;
    public uint version;
    public uint width;
    public uint height;
    public uint format;
    public uint alpha;
    public uint origin;
    public uint reserved;
    public ulong stride;
    public ulong generation;
    public ulong size_generation;
    public ulong sequence;
    public uint hotspot_x;
    public uint hotspot_y;
    public tidyvnc_bytes pixels;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_prompt_info
{
    public uint size;
    public uint version;
    public uint kind;
    public uint secure;
    public uint username_required;
    public uint certificate_status;
    public ulong id;
    public ulong generation;
    public tidyvnc_bytes server_name;
    public tidyvnc_bytes identity;
    public tidyvnc_bytes fingerprint;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_certificate_key_info
{
    public uint size;
    public uint version;
    public tidyvnc_bytes spki;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_key_digest
{
    public uint size;
    public uint version;
    public uint length;
    public uint reserved;
    public fixed byte bytes[64];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_certificate_policy
{
    public uint size;
    public uint version;
    public uint reasons;
    public uint fatal_status;
    public uint may_override;
    public uint reserved;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_callbacks
{
    public uint size;
    public uint version;
    public void* context;
    public delegate* unmanaged[Cdecl]<void*, void> retain_context;
    public delegate* unmanaged[Cdecl]<void*, void> release_context;
    public delegate* unmanaged[Cdecl]<void*, ulong, ulong, void> ready;
    public ulong reserved;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_scaling
{
    public uint size;
    public uint version;
    public uint mode;
    public uint x;
    public uint y;
    public uint fits;
    public fixed byte canonical[64];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_tile_options
{
    public uint size;
    public uint version;
    public uint width;
    public uint height;
    public uint quality;
    public uint reserved;
    public uint x;
    public uint y;
    public uint tile_width;
    public uint tile_height;
    public ulong previous_sequence;
    public uint damage_x;
    public uint damage_y;
    public uint damage_width;
    public uint damage_height;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_tile_result
{
    public uint size;
    public uint version;
    public uint cache_hit;
    public uint reserved;
    public ulong cache_bytes;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_cursor_options
{
    public uint size;
    public uint version;
    public uint quality;
    public uint reserved;
    public double scale_x;
    public double scale_y;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_cursor_geometry
{
    public uint size;
    public uint version;
    public uint width;
    public uint height;
    public uint hotspot_x;
    public uint hotspot_y;
    public uint blank;
    public uint reserved;
    public ulong source_bytes;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_cursor_tile
{
    public uint size;
    public uint version;
    public uint x;
    public uint y;
    public uint width;
    public uint height;
    public fixed uint reserved[2];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_geometry_options
{
    public uint size;
    public uint version;
    public uint remote_width;
    public uint remote_height;
    public uint units;
    public uint reserved;
    public double viewport_width;
    public double viewport_height;
    public double backing_scale;
    public double pan_x;
    public double pan_y;
    public tidyvnc_bytes scaling;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_geometry
{
    public uint size;
    public uint version;
    public uint backing_width;
    public uint backing_height;
    public double x;
    public double y;
    public double width;
    public double height;
    public int remote_x;
    public int remote_y;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_canvas_viewport
{
    public uint size;
    public uint version;
    public uint width;
    public uint height;
    public uint x;
    public uint y;
    public uint region_width;
    public uint region_height;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_damage
{
    public uint size;
    public uint version;
    public uint x;
    public uint y;
    public uint width;
    public uint height;
    public uint quality;
    public uint reserved;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_rectangle
{
    public uint size;
    public uint version;
    public double x;
    public double y;
    public double width;
    public double height;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_clipboard_route
{
    public uint size;
    public uint version;
    public ulong session;
    public ulong generation;
    public ulong focus_revision;
    public ulong policy_revision;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_clipboard_update
{
    public uint size;
    public uint version;
    public uint kind;
    public uint result;
    public ulong sequence;
    public tidyvnc_clipboard_route route;
    public ulong text;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_clipboard_info
{
    public uint size;
    public uint version;
    public uint from_remote;
    public uint reserved;
    public tidyvnc_clipboard_route route;
    public tidyvnc_bytes text;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_identity_request
{
    public uint size;
    public uint version;
    public uint kind;
    public uint security_type;
    public uint shape;
    public uint allow_unix_sockets;
    public uint port;
    public uint reserved;
    public tidyvnc_bytes endpoint;
    public tidyvnc_bytes route;
    public tidyvnc_bytes username;
    public tidyvnc_bytes host_key_alias;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_identity
{
    public uint size;
    public uint version;
    public fixed byte text[80];
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_ssh_gateway_info
{
    public uint size;
    public uint version;
    public uint port;
    public uint flags;
    public tidyvnc_bytes host;
    public tidyvnc_bytes scope;
    public tidyvnc_bytes user;
    public tidyvnc_bytes canonical_uri;
}

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct tidyvnc_desktop_size
{
    public uint size;
    public uint version;
    public uint width;
    public uint height;
}

[InlineArray(2)]
public struct tidyvnc_listener_address_Array2
{
    private tidyvnc_listener_address _element0;
}

[InlineArray(255)]
public struct tidyvnc_remote_screen_Array255
{
    private tidyvnc_remote_screen _element0;
}

[InlineArray(64)]
public struct tidyvnc_remote_screen_Array64
{
    private tidyvnc_remote_screen _element0;
}

/// <summary>Every tidyvnc_viewer.dll export, in header order.</summary>
public static unsafe partial class NativeMethods
{
    public const string Library = "tidyvnc_viewer";

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_host_key_validate(tidyvnc_bytes key, uint* bits, tidyvnc_error* error);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_certificate_key_create(tidyvnc_bytes p0, ulong* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_certificate_key_get(ulong p0, tidyvnc_certificate_key_info* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_certificate_key_digest(ulong p0, uint p1, tidyvnc_key_digest* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_certificate_policy_get(uint p0, tidyvnc_certificate_policy* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_clipboard_policy(ulong p0, ulong generation, uint send, uint receive, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_clipboard_offer(ulong p0, ulong generation, tidyvnc_bytes text, ulong origin, ulong change_id, tidyvnc_operation* p5, tidyvnc_error* p6);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_clipboard_clear(ulong p0, ulong generation, tidyvnc_operation* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_take_clipboard(ulong p0, tidyvnc_clipboard_update* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_clipboard_get(ulong text, tidyvnc_clipboard_info* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_clipboard_check(ulong p0, tidyvnc_clipboard_route* p1, uint sending, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_get_abi(tidyvnc_abi_info* p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_security_choice_at(uint index, tidyvnc_security_choice* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_tls_priority_validate(tidyvnc_bytes p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_sharing(ulong p0, tidyvnc_sharing* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_set_shared(ulong p0, ulong generation, ulong revision, uint shared, ulong* new_revision, tidyvnc_error* p5);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_security(ulong p0, tidyvnc_security_configuration* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_set_security(ulong p0, ulong generation, ulong revision, tidyvnc_security_update* p3, ulong* new_revision, tidyvnc_error* p5);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_security_resolve(tidyvnc_bytes text, uint defaults, tidyvnc_security_selection* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_renderer_create(ulong cache_bytes, ulong* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_renderer_clear(ulong p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_renderer_render(ulong p0, ulong image, tidyvnc_tile_options* p2, tidyvnc_mutable_bytes output, tidyvnc_tile_result* p4, tidyvnc_error* p5);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_cursor_renderer_create(ulong image, tidyvnc_cursor_options* p1, ulong* p2, tidyvnc_cursor_geometry* p3, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_cursor_renderer_render(ulong p0, tidyvnc_cursor_tile* p1, tidyvnc_mutable_bytes p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_scaling_parse(tidyvnc_bytes p0, tidyvnc_scaling* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_desktop_damage(tidyvnc_geometry_options* p0, tidyvnc_damage* p1, tidyvnc_rectangle* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_desktop_geometry(tidyvnc_geometry_options* p0, double point_x, double point_y, tidyvnc_geometry* p3, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_desktop_canvas_geometry(tidyvnc_geometry_options* p0, tidyvnc_canvas_viewport* p1, double pointer_x, double pointer_y, tidyvnc_geometry* p4, tidyvnc_error* p5);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_desktop_canvas_damage(tidyvnc_geometry_options* p0, tidyvnc_canvas_viewport* p1, tidyvnc_damage* p2, tidyvnc_rectangle* p3, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_retain(ulong p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_release(ulong p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_runtime_options_init(tidyvnc_runtime_options* p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_logging_validate(tidyvnc_bytes policy, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_logging_viewport(uint logical_width, uint logical_height, uint backing_width, uint backing_height, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_logging_configure(tidyvnc_bytes policy, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_logging_configure_with_file(tidyvnc_bytes policy, tidyvnc_bytes file_path, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_options_init(tidyvnc_session_options* p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_connect_options_init(tidyvnc_connect_options* p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_runtime_create(tidyvnc_runtime_options* p0, ulong* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_runtime_shutdown(ulong p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_runtime_poll_drained(ulong p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_listener_options_init(tidyvnc_listener_options* p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_listener_create(ulong runtime, tidyvnc_listener_options* p1, ulong* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_listener_get_snapshot(ulong p0, tidyvnc_listener_snapshot* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_listener_take_event(ulong p0, tidyvnc_listener_event* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_listener_reject(ulong p0, ulong incoming_id, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_listener_accept(ulong listener, ulong incoming_id, ulong session, tidyvnc_operation* p3, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_listener_stop(ulong p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_listener_poll_drained(ulong p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_listener_subscribe(ulong p0, tidyvnc_callbacks* p1, ulong* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_create(ulong runtime, tidyvnc_session_options* p1, ulong* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_information(ulong session, ulong generation, tidyvnc_connection_info* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_endpoint_validate(tidyvnc_bytes endpoint, uint allow_unix_sockets, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_endpoint_create(tidyvnc_bytes endpoint, tidyvnc_bytes route, uint allow_unix_sockets, ulong* p3, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_endpoint_get(ulong p0, tidyvnc_endpoint_info* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_port_parse(tidyvnc_bytes p0, uint* port, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_native_error_category(int native_error, uint* category, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_identity_digest(tidyvnc_identity_request* p0, tidyvnc_identity* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_ssh_gateway_create(tidyvnc_bytes p0, ulong* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_ssh_gateway_get(ulong p0, tidyvnc_ssh_gateway_info* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_document_parse(tidyvnc_bytes p0, ulong* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_invocation_parse(tidyvnc_bytes* p0, uint count, ulong* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_invocation_validate(ulong p0, ulong* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_invocation_get(ulong p0, tidyvnc_invocation_info* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_invocation_assignment_at(ulong p0, uint index, tidyvnc_invocation_assignment* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_invocation_option_at(uint index, tidyvnc_invocation_option* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_document_get(ulong p0, tidyvnc_document_info* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_document_entry_at(ulong p0, uint index, uint decode_value, tidyvnc_document_entry* p3, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_document_option_at(ulong p0, uint index, tidyvnc_document_entry* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_document_serialize(tidyvnc_document_assignment* p0, uint count, tidyvnc_mutable_bytes output, ulong* size, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_encoding_schema_at(uint index, tidyvnc_encoding_schema* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_encoding_choice_at(uint index, tidyvnc_encoding_choice* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_encoding_create(ulong @base, tidyvnc_encoding_assignment* p1, uint count, uint source, ulong* p4, tidyvnc_error* p5);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_encoding_get(ulong p0, uint option, tidyvnc_encoding_value* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_create_with_encoding(ulong runtime, tidyvnc_session_options* p1, ulong encoding, ulong* p3, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_input_timing_init(tidyvnc_input_timing* p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_create_with_input_timing(ulong runtime, tidyvnc_session_options* p1, ulong encoding, tidyvnc_input_timing* p3, ulong* p4, tidyvnc_error* p5);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_window_geometry_parse(tidyvnc_bytes p0, tidyvnc_window_geometry* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_desktop_size_parse(tidyvnc_bytes p0, uint syntax, tidyvnc_desktop_size* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_message_limits_init(tidyvnc_message_limits* p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_create_with_message_limits(ulong runtime, tidyvnc_session_options* p1, ulong encoding, tidyvnc_input_timing* p3, tidyvnc_message_limits* p4, ulong* p5, tidyvnc_error* p6);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_encoding(ulong p0, ulong* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_apply_encoding(ulong p0, ulong generation, ulong encoding, tidyvnc_operation* p3, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_connect(ulong p0, tidyvnc_connect_options* p1, tidyvnc_operation* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_connect_routed(ulong p0, ulong target, tidyvnc_connect_options* p2, tidyvnc_operation* p3, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_disconnect(ulong p0, ulong generation, tidyvnc_operation* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_refresh(ulong p0, ulong generation, tidyvnc_operation* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_display_layout_compute(tidyvnc_display_layout_request* p0, tidyvnc_display_layout* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_desktop_layout_validate(tidyvnc_desktop_layout_request* p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_desktop_layout(ulong p0, ulong generation, tidyvnc_desktop_layout* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_request_desktop_layout(ulong p0, ulong generation, tidyvnc_desktop_layout_request* p2, tidyvnc_operation* p3, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_cancel_operation(ulong p0, ulong generation, ulong operation, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_close(ulong p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_poll_drained(ulong p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_snapshot(ulong p0, tidyvnc_snapshot* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_subscribe(ulong p0, tidyvnc_callbacks* p1, ulong* p2, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_subscription_unsubscribe(ulong p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_subscription_poll_drained(ulong p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_subscription_validate(ulong p0, ulong generation, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_take_event(ulong p0, tidyvnc_event* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_take_view(ulong p0, tidyvnc_view_update* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_image_get(ulong p0, tidyvnc_image_info* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_key(ulong p0, ulong generation, uint key_id, uint keysym, uint keycode, uint down, tidyvnc_error* p6);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_pointer(ulong p0, ulong generation, int x, int y, uint buttons, tidyvnc_error* p5);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_focus(ulong p0, ulong generation, uint focused, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_release_input(ulong p0, ulong generation, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_view_only(ulong p0, uint enabled, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_input_policy(ulong p0, uint view_only, uint emulate_middle, tidyvnc_error* p3);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_shortcut_create(uint modifiers, ulong* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_shortcut_modifiers(ulong p0, uint modifiers, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_shortcut_key(ulong p0, int physical_id, uint keysym, uint down, uint* action, tidyvnc_error* p5);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_shortcut_reset(ulong p0, tidyvnc_error* p1);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_take_prompt(ulong p0, ulong* prompt, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_prompt_get(ulong p0, tidyvnc_prompt_info* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_prompt_security_type(ulong p0, uint* p1, tidyvnc_error* p2);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_reply_credentials(ulong p0, ulong id, ulong generation, tidyvnc_mutable_bytes username, tidyvnc_mutable_bytes password, tidyvnc_error* p5);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_reply_credential_bytes(ulong p0, ulong id, ulong generation, tidyvnc_mutable_bytes username, tidyvnc_mutable_bytes password, tidyvnc_error* p5);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_reply_password_file(ulong p0, ulong id, ulong generation, tidyvnc_mutable_bytes obfuscated, tidyvnc_error* p4);

    [LibraryImport(Library)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial uint tidyvnc_session_reply_trust(ulong p0, ulong id, ulong generation, uint allowed, tidyvnc_error* p4);
}
